plugin:
  discord_enabled:
    default: true
    client: true
  discord_client_id:
    default: ''
    client: true
  discord_bot_token: ''
  discord_guild_id: ''
  discord_sync_role_name: ''
  discord_sync_trust_level:
    default: ''
    client: true
